name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      # Uncomment if tests are required
      # - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host Backend
            HostName ${{ secrets.EC2_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Install Node.js and TSX on EC2
        run: |
          ssh Backend "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs"
          ssh Backend "npm install -g tsx"

      - name: Copy Workspace
        run: |
          scp -r ./* Backend:/home/ubuntu/app/

      - name: Install dependencies on EC2
        run: |
          ssh Backend "cd /home/ubuntu/app && npm ci"

      - name: Start the application with PM2
        run: |
          ssh Backend "pm2 delete umc-7th-app || true"
          ssh Backend "pm2 start /home/ubuntu/app/src/index.ts --name 'umc-7th-app' --interpreter=tsx"

