name: deploy-main

on:
  push:
    branches:
      - main
      - hotfix/fix-cicd-pipe
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prisma has changes
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host msmg-umc
            HostName $EC2_HOST
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh msmg-umc 'sudo mkdir -p /opt/app'
          ssh msmg-umc 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* msmg-umc:/opt/app

      - name: Install dependencies
        run: |
          ssh msmg-umc 'cd /opt/app; npm ci'
          ssh msmg-umc 'cd /opt/app; npm exec prisma generate'
          ssh msmg-umc 'cd /opt/app; node swagger.js'

      - name: Apply prisma migrations
        if: steps.paths-filter.outputs.prisma == 'true'
        run: |
          ssh msmg-umc 'cd /opt/app; npm exec prisma migrate deploy'

      - name: Start or Restart PM2 Process
        run: |
          ssh msmg-umc "
            pm2 delete umc-7th-app || true
            pm2 start /opt/app/src/index.ts --name 'umc-7th-app' --interpreter=tsx
            pm2 save
          "
